### ISSUE TITLE
Batch processing for FaissKNNClassifier kneighbors method

### ISSUE THREAD

**Issue by luizgh** [scikit-learn-contrib/DESlib#103]

**Comment by Menelau** [comment]
@luizgh Do you know what is the problem exactly with the `kneighbors` method? For what I check it seems to be ok. 

Other methods in the class (ex `predict_proba`) were still working with a `for` loop inside. However, I just changed that in commit: d524553907c8507789dcdaae816792beeaecb9d2

**Comment by Natlem** [comment]
That for loop was the problem. 

-- 
Thanh
