### ISSUE TITLE
Allow approximate NN searchs on the FaissKNNClassifier class

### ISSUE THREAD

**Issue by Menelau** [scikit-learn-contrib/DESlib#140]
The current FaissKNNClassifier class only perform brute force search. The class should also allow approximate methods in order to speed up inference time on large datasets.

More info about approximate search on faiss can be found in the following links: https://github.com/facebookresearch/faiss/wiki/Getting-started and https://github.com/facebookresearch/faiss/wiki/Faster-search

**Comment by Natlem** [comment]
I think we should do a comparison first before actually implementing it right ? Since, there's no point in adding it if it does not improve the speed

**Comment by Natlem** [comment]
Checking up on this again, I re-read the code a bit, we can allow approximate search if we pass one of the indexes from https://github.com/facebookresearch/faiss/wiki/Faiss-indexes using the algorithm parameter of FaissKNNClassifier

**Comment by Menelau** [comment]
Yes! I believe this is the best option. That would be similar to sklearn KNN which the algorithm parameter is used to select between different implementations (kdtree, ball-trees, brute...). 

In this case, we need to check which approximations are relevant to add as options. For what I saw, the `IndexIVFFlat` approximation is a good candidate since it is much faster than the brute force and it does not increase the memory requirements. The `IndexHNSWFlat` requires way more memory but maybe it can also be an option to medium or medium to large sized datasets.

**Comment by Menelau** [comment]
@Natlem will you work on this issue?

**Comment by Natlem** [comment]
Yes, but we need to decide a way to pass the argument first. We can pass some simple approximate NN searches using the algorithm parameter but some advanced approximate NN searches require other parameters (i.e IndexIVFFlat) . I was thinking we can pass them by kwargs but I don't know if that a good idea. What do you think ?

**Comment by Menelau** [comment]
Checking the documentation of IndexIVFFlat, it seems the number of cells (nlist) and number of probes (nprobes) are important to set in this search.

So I believe we should just list these new input parameters in init with a sensible default value and explain in the documentation that they are only used if the algorithm='IndexIVFFlat' (Maybe we can give a better name for this like "voronoi"). I believe that would be better and also more sklearn way than use kwargs.
