### ISSUE TITLE
Run DESlib on Python 2.x.x

### ISSUE THREAD

**Issue by raniel90** [scikit-learn-contrib/DESlib#150]
DESlib requires Python '>=3' but the running Python is 2.7.15

I need to run my project on Python 2.7.15. How can i install this lib in this python version?

**Comment by luizgh** [comment]
Hi @raniel90. The DESlib library requires Python 3, so you would need to migrate your code to Py3 (tools such as 2to3 can help this: https://docs.python.org/2/library/2to3.html). Please note that numpy (that DESlib depends on) is ending its support to Python 2 (new numpy features are only available for Python 3 as of this year, and they will remove support next year: https://docs.scipy.org/doc/numpy-1.14.2/neps/dropping-python2.7-proposal.html), so migration to Python 3 is recommended.
