### ISSUE TITLE
Why the competence estimation in OLA is different from the paper?

### ISSUE THREAD

**Issue by sara-eb** [scikit-learn-contrib/DESlib#162]
Hi everyone, 

Does anyone knows why in the competence estimation in OLA in [this line](https://github.com/scikit-learn-contrib/DESlib/blob/master/deslib/dcs/ola.py#L149), the fraction of correct predictions from `self.DES_processed_` is calculated: competences=(#TRUEs)/(#TRUEs and #FALSEs). However, in the paper "Dynamic classifier selection: Recent advances and perspectives" (Section 4.2), the authors are mentioning that the mean of Posterior probability (P) is calculated. What is the reason for this contradiction? 

Thanks

**Comment by Menelau** [comment]
Hello,

The original OLA implementation is the percentage of correct classification. Checking the paper again, the notation there is confusing/misleading.

**Comment by sara-eb** [comment]
@Menelau Thanks for your reply. Then, if I am not mistaken,  the percentage of correct classification in the implementation should be followed?

**Comment by Menelau** [comment]
yes, the percentage of correct classification in the region of competence should be followed.

**Comment by sara-eb** [comment]
@Menelau  Thanks a lot for confirming
