### ISSUE TITLE
Calibration predict_proba

### ISSUE THREAD

**Issue by lachhebo** [scikit-learn-contrib/DESlib#163]
Hello, 

Let say one uses several Random forest models with DESClustering, then he uses predict proba. 

Does the probability estimates between the estimators are calibrated ? 
If no, we need to do it before fitting them to the DesClustering model ?

**Comment by Menelau** [comment]
Hello,

The probability estimates are not calibrated inside the model, they need to be calibrated before.

**Comment by lachhebo** [comment]
Okay, thank you.
