### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by zaimonash** [scikit-learn-contrib/DESlib#164]
I'm getting this error in Jupyter Notebook

_...\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)_

_...\Anaconda3\lib\site-packages\sklearn\calibration.py:455: RuntimeWarning: invalid value encountered in multiply
  TEP_minus_T1P = P * (T * E - T1)_

_...\Anaconda3\lib\site-packages\sklearn\calibration.py:455: RuntimeWarning: invalid value encountered in multiply
  TEP_minus_T1P = P * (T * E - T1)_

_...\PhD\Anaconda3\lib\site-packages\sklearn\calibration.py:455: RuntimeWarning: invalid value encountered in multiply
  TEP_minus_T1P = P * (T * E - T1)_

_...\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)_

_...\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)_

_...\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)_

_...\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)_

_...\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)_

_...\Anaconda3\lib\site-packages\deslib\des\probabilistic\base.py:191: RuntimeWarning: invalid value encountered in true_divide
  competences = competences / sum_potential.reshape(-1, 1)_

_...\Anaconda3\lib\site-packages\deslib\des\probabilistic\base.py:222: RuntimeWarning: invalid value encountered in greater
  selected_classifiers = (competences > selection_threshold)_

**Comment by zaimonash** [comment]
I used the Jupyter example provided at the DESlib website and simply run it on Jupyter Notebook. No changes made.

**Comment by zaimonash** [comment]
Yes. The one with heterogeneous classfiers

**Comment by zaimonash** [comment]
I run the original file without any modification.

**Comment by Menelau** [comment]
Fixed in #165
