### ISSUE TITLE
Bayesian Network

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#172]
How do I implement Bayesian Network since it not available in scikit learn?

**Comment by Menelau** [comment]
@jayahm Hello,

Sorry for the late response. Unfortunately this library is focused only on ensemble models (more specifically on dynamic ensembles). So, Bayesian Networks is not on the scope of this library. 

There are other python libraries with implementation of Bayesian Network that you should try:

- Python Library for Probabilistic Graphical Models (pgmpy): https://github.com/pgmpy/pgmpy
- BayesPy: http://bayespy.org/
