### ISSUE TITLE
Region of competence

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#175]
How do define the region of competence using clustering method?

**Comment by Menelau** [comment]
Hello, In the DESClusterigng estimator the region of competence is based on the K-Means clustering algorithm over the training data. 

The region of competence of a given `x_test ` is defined by the cluster with the nearest centroid.

**Comment by jayahm** [comment]
So, there is no clustering approach for defining the region on OLA, LCA and etc methods?

**Comment by Menelau** [comment]
Hello @jayahm 

Unfortunately, these methods can only work with KNN as the implementation of these methods was made following the original publications.

I have plans in the future to refactor the library in a way that all methods could select clustering as a method for defining the region of competence.

**Comment by jayahm** [comment]
@Menelau That is great. It would be great if that is possible as more explorations can be carried out.
