### ISSUE TITLE
'StaticSelection' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#183]
Hi,

It seems like other methods have `predict_proba` but not for `StaticSelection`.

https://deslib.readthedocs.io/en/latest/modules/static/static_selection.html

It would be good if I can get the probability score of this method.

**Comment by Menelau** [comment]
@jayahm,

Thanks for reporting this issue! I just added the method in the PR #185
