### ISSUE TITLE
'Oracle' has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#186]
Hi,

It seems like Oracle has no attribute `predict_proba` too.

https://deslib.readthedocs.io/en/latest/modules/static/oracle.html

It would be good if I can get the probability score of this method too.

**Comment by jayahm** [comment]
Any update?

**Comment by Menelau** [comment]
I'm checking how this functionality should be implemented as predict_proba for the Oracle (as it is an abstract model) is not defined. I will give you an update on that in the weekend

**Comment by Menelau** [comment]
Fixed in PR #188
