### ISSUE TITLE
Couldn't find META-DES Oracle?

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#197]
Hi,

I say METAS-DES oRacle is one of the methods presented the paper.

But, I couldn't find it this library.

**Comment by Menelau** [comment]
Hello,

META-DES.Oracle is not available yet. It currently in development (see branch: https://github.com/scikit-learn-contrib/DESlib/tree/meta_des_oracle). It will be available in the next version.
