### ISSUE TITLE
Unable to find "Dynamic Selection on Complexity"

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#199]
Hi,

Is this technique available in this library?
Dynamic Selection on Complexity

**Comment by Menelau** [comment]
@jayahm  Hello,

No, this technique is not available in the library yet. If you can contribute to an implementation of this method let me know.

**Comment by jayahm** [comment]
Oh, it's not available. But I saw it has been tested in your paper "Dynamic classifier selection: Recent advances and perspectives"

**Comment by Menelau** [comment]
It was evaluated in the review paper, however, based on the original implementation provided by the author. I have plans to have this method added to the library in the future, however, there are some things in its implementation I still need to think about how to put in the context of the library  (such as the way they use dataset complexity measures in the competence estimation etc).
