### ISSUE TITLE
Unable to find the information on DES-Logarithmic and DES-Exponential in the references listed

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#202]
I was trying to understand the above two methods.

After checking in the references listed in the API Reference's page, I couldn't find the information about these two methods:

```
1. B. Antosik, M. Kurzynski, New measures of classifier competence – heuristics and application to the design of multiple classifier systems., in: Computer recognition systems 4., 2011, pp. 197–206.
2. T.Woloszynski, M. Kurzynski, A measure of competence based on randomized reference classifier for dynamic ensemble selection, in: International Conference on Pattern Recognition (ICPR), 2010, pp. 4194–4197.
```

So, where I can read more about the two methods?

**Comment by Menelau** [comment]
Hello,

You can read more about those two methods in the following paper:

**Woloszynski, Tomasz, and Marek Kurzynski. "On a new measure of classifier competence applied to the design of multiclassifier systems." In International Conference on Image Analysis and Processing, pp. 995-1004. Springer, Berlin, Heidelberg, 2009.**

I will update the documentation with this paper.

Also, the DES-logarithmic corresponds to Method 1 in the paper you mentioned above:  

2. T.Woloszynski, M. Kurzynski, A measure of competence based on randomized reference classifier for dynamic ensemble selection, in: International Conference on Pattern Recognition (ICPR), 2010, pp. 4194–4197.

**Comment by jayahm** [comment]
I'll have a look. Thank you.
