### ISSUE TITLE
For LCA, what if the samples with the class is not amongst the neighbour?

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#205]
I'm wondering for LCA.

Since the local accuracy is estimated in respect of output classes assigned by a particular classifier, what if the local region of a test sample does not have the validation sample with that class label in the region?

Is this possible to happen?

If yes, how your implementation for LCA can handle this?

**Comment by Menelau** [comment]
Yes, it is possible to happen. In this case, the competence level of this
base classifier is set to zero

Em qui., 6 de ago. de 2020 às 21:48, jayahm <notifications@github.com>
escreveu:

**Comment by jayahm** [comment]
@Menelau 

May I know which part of the library is doing so?

**Comment by Menelau** [comment]
In the **estimate_competence** function line 180:

https://github.com/scikit-learn-contrib/DESlib/blob/50e6ba4ddc8f04599937ac0b9913522798dd4b58/deslib/dcs/lca.py#L180
