### ISSUE TITLE
How do I know the aggregation technique used for each DES method?

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#206]
Hi,

As mentioned in your review paper, there are several types of aggregation technique for DES.

But, upon checking each code of the DS methods in deslib, I couldn't find the information on the aggregation used by each method.

Did I miss the information somewhere?

**Comment by Menelau** [comment]
Hello,

All methods use majority voting as aggregation rule.

**Comment by jayahm** [comment]
Thanks for the clarification
