### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#211]
Hi,

For DS methods, does the training time should include the training time of each base classifier?

Is it like this?
`training_time = time_clf1 + time_clf2 + ... + time_clfn + time_the_ds_ method`

**Comment by Menelau** [comment]
@jayahm 

It depends on what do you want to measure. If you want to measure the training time of your whole system, for example, to compare with different state-of-the-art approaches (like with the training of a single classifier) for the same application you will need to add the time for training the base classifiers as well. 

If you just want to measure the training time of the DS method to compare with other ensemble combination approaches (which is independent of the base models), training of the base models should no be included.

**Comment by jayahm** [comment]
I wanted to compare the whole system with single classifiers as well. Thank you. I got your point.
