### ISSUE TITLE
Pool based on different features

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#218]
Hi,

Is there any example on how to perform DS based on different features?

The examples on the website are only cover on pool of heterogeneous classifiers, bagging and random forest.

I couldn't find and have no idea on how to generatea pool of different features.

**Comment by Menelau** [comment]
@jayahm Hello,

At the moment the library can only work with all models receiving the same feature set as input. There are ways to have base classifiers using different transformations of the input features set by using a sklearn pipeline (for example use a subset of the input features or transformations such as PCA). In this case, each base model should be composed of a scikit-learn Pipeline in which the first component is the transformation applied to the input features and the last component is the classifier model. 

I will create an example showing this functionality.

**Comment by jayahm** [comment]
How about Random Subspace Method?

I was thinking to try this.

**Comment by Menelau** [comment]
fixed in #254

**Comment by jayahm** [comment]
Hi,

I just realized the issue has been fixed. But, I'm not sure how to start applying it
