### ISSUE TITLE
DES-P

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#219]
Hi,

As far as I understood, DES-P is a probabilistic method, but why it is not included the probabilistic methods in this library?

**Comment by Menelau** [comment]
This method does not follow the same structure from the probabilistic ones. It does not use the potential function model in the region of competence steps. That is the reason it is out.

**Comment by jayahm** [comment]
So, it is still a probabilistic DS method right?

**Comment by jayahm** [comment]
Hi,

I would like to re-open this.

Upon checking, the code to compute the competence is:

`competences = np.mean(self.DSEL_processed_[neighbors, :], axis=1)`

This is measuring the accuracy right?

What I understood, it is based on probability.

Am I wrong somewhere?

**Comment by Menelau** [comment]
This method is based solely on accuracy. It does not use the classifier's
probabilities.

Em ter., 13 de out. de 2020 às 23:48, jayahm <notifications@github.com>
escreveu:

**Comment by jayahm** [comment]
But, based on your paper, it was written probabilistic?

**Comment by Menelau** [comment]
It's an error in the paper.

Em qua., 14 de out. de 2020 às 00:37, jayahm <notifications@github.com>
escreveu:

**Comment by jayahm** [comment]
So, can I consider it as an accuracy-based method?

**Comment by Menelau** [comment]
Yes, it is an accuracy based method. It simply selects the base classifiers that have local accuracy higher than random predictions.

**Comment by jayahm** [comment]
I see. Thanks!

**Comment by jayahm** [comment]
How about DES-KL? Is it accuracy-based DES too?
