### ISSUE TITLE
Why self.DSEL_target_ is not the same as the original class labels?

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#231]
Hi,

My original class label is 0 and 3.

But, when Ic checked using self.DSEL_target_, it was 0 and 1.

Does DESlib convert it to this kind of values or there is something wrong in the way I'm using the library?

**Comment by Menelau** [comment]
We use label encoder to automatically convert labels for faster processing
inside of the models (indexing arrays, so it needs to be sequential) as is
done in any scikit-learn model. That is also performed as a way to deal
with classes that are strings (e.g., cat, dogs).

Em ter., 13 de out. de 2020 às 23:45, jayahm <notifications@github.com>
escreveu:

**Comment by jayahm** [comment]
I see.

Thank very much!
