### ISSUE TITLE
Different types of combiners

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#235]
Hi,

I notice that there is aggregation class in util

But, how do I change the aggregation strategy, for example, suing weighted MV for DES methods?

**Comment by Menelau** [comment]
@jayahm Hello,

In this case, you will need to change the source code to use a different aggregation function. Other aggregation strategies were not added to the DS methods in order to simplify the code.

**Comment by jayahm** [comment]
So, in case I wanted to use weighted MV from [util](https://github.com/scikit-learn-contrib/DESlib/blob/master/deslib/util/aggregation.py), how do I get started?

**Comment by Menelau** [comment]
You should go to the file **deslib/des/base.py** and get familiar with the **classify_with_ds** and **predict_proba_with_ds** methos. Then, you can change the combination scheme from the majority voting to the desired one.
