### ISSUE TITLE
Different ways for defining region of competence

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#236]
Hi,

It is known that we can apply adaptive KNN to define the region of competence.

But, how do I apply such a technique to define the region of competence?

How about other types of KNN? I can only see the way to use KNN-Equality in this library.

I there any possibilities to use other types of KNN?

**Comment by Menelau** [comment]
@jayahm 

Other types of KNN is not available in the library and adding variations is not on plan for the near future. If you want to use a different method you will need to get the library source code and add your own implementation of such methods. In this case, you will need to change the code that performs the region of competence estimation to the method you want.

**Comment by jayahm** [comment]
OK. In case I want to use DESlib existing methods such as OLA, LCA, DES-P and etc, which file I go and change the implementation fo region of competence definition?

**Comment by Menelau** [comment]
region of competence definition code is on the BaseDS class (all other methods inherit from it). So you must go to this class which is located in **deslib/base.py** and modify the source code to use a different KNN algorithm.
