### ISSUE TITLE
Can we change the threshold for META-DES?

### ISSUE THREAD

**Issue by jayahm** [scikit-learn-contrib/DESlib#239]
Hi,

Can I use a different threshold for META-DES?

If yes, what actually the criteria to set the threshold?

If no, why it should be always 0.5?

**Comment by Menelau** [comment]
Hello,

Yes you can change the competence threshold (**selection_threshold**) so that the method becomes either more (increasing the threshold) or less strict. You can check that in the method's documentation how to do it: https://deslib.readthedocs.io/en/latest/modules/des/meta_des.html
