### ISSUE TITLE
DES Voting parameter issue

### ISSUE THREAD

**Issue by atifov** [scikit-learn-contrib/DESlib#260]
I would like to change the **_"voting''_** hyperparameter in the DES models. However, whenever I change the voting hyperparameter, I get an error. The code and error are as follows: 

_model = KNOP(pool_classifiers=classifiers, voting='soft')_

_TypeError: __init__() got an unexpected keyword argument 'voting'_

Please note that I have been able to change the other hyperparameters, this is the only exception.

Your help on this matter will be highly appreciated. Thanks

**Comment by Menelau** [comment]
@atifov Hello,

Which version of the library are you using? The stable version (0.3.5) or the one installed based on the master code (dev)? Can you try installing the master version with the command:

pip install git+https://github.com/scikit-learn-contrib/DESlib

and see if it works?

**Comment by atifov** [comment]
I checked the version of library, it's the latest version 0.3.5.

Following are the commands and results:

_import deslib
print(deslib.__version__)
0.3.5_

**Comment by atifov** [comment]
Following your advice and installing the master version, the issue has been resolved. Thanks a lot.
