### ISSUE TITLE
How to get the estimate_competence

### ISSUE THREAD

**Issue by ItsHaiming** [scikit-learn-contrib/DESlib#263]
Hi
I'm using KNORA-U to do the classification problem. I hope to get the final classifier chosen from the classifier pool, and I can see from the document that there are functions like `"estimate_competence(competence_region, distances=None, predictions=None)"` and `"select(competences)"` to achieve this. But I'm confused about the parameter" competence_region", is there any example or explanation for this?

Many thanks!

**Comment by ItsHaiming** [comment]
Is that mean, I should create an array, with the index of k nearest neighbors? should I use KNN to find the parameter?

**Comment by Menelau** [comment]
Hello,

Yes, the competence region is the array with the K-nearest neighbours for all testing instances. you can obtain this array calling the **_get_region_competence** function in the library.
