### ISSUE TITLE
Allow other KNN implementations in the DS base class

### ISSUE THREAD

**Issue by luizgh** [scikit-learn-contrib/DESlib#6]
Allow other KNN implementations (such as KNN-Equality KNNE, the FAISS implementation of KNN)

**Comment by luizgh** [comment]
(being implemented in https://github.com/Natlem/DESlib/tree/faiss_integration)

**Comment by luizgh** [comment]
We are planing on implementing this feature in a way that the caller can use any KNN function they want. Something like this:

```python
def __init__(self, (...), roc_algorithm=None):
    if roc_algorithm:
        self.roc_algorithm = KNeighborsClassifier
    elif isinstance(roc_algorithm, str):
        if roc_algorithm == 'knn':
            self.roc_algorithm = KNeighborsClassifier
        elif roc_algorithm == 'faiss':
            self.roc_algorithm = FAISSKNNClassifier
        else:
            raise ValueError('Invalid algorithm ...')
    elif callable(roc_algorithm):
        self.roc_algorithm = roc_algorithm
    else:
        raise ValueError('Invalid algorithm ...')
```

Then in the ```fit_region_competence``` method, we would simply use the chosen class:

```python
self.roc_ =self.roc_algorithm(n_neighbors=k, n_jobs=-1, algorithm='auto')
```

This would make it easy for the user to use the most common cases (knn, fast_knn by faiss), while being flexible to allow any other method. 

About KNN-E, if we already have a reference implementation (or a paper describing it), we can include it as one of the "common cases" (i.e. allow the user to inform roc_algorithm='knn-e' or similar).

**Comment by Natlem** [comment]
There's also FAISS K-MEANS for des-clustering

**Comment by luizgh** [comment]
https://github.com/Menelau/DESlib/pull/94 implemented it for the base class, but there are classes that fit a KNN on the output profiles (e.g. META-DES, KNOP). These should also use the KNN method that was selected by the user.

**Comment by Natlem** [comment]
Fixed in https://github.com/Menelau/DESlib/pull/102
